# Ligação ao Neon PostgreSQL via variáveis de ambiente
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_course
spring.datasource.username=postgres
spring.datasource.password=admin

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# JWT (caso esteja a utilizar no projeto - segredo seguro com mais de 256 bits)
jwt.secret=${JWT_SECRET:dGhpc2lzYXNhZmVhbmR2ZXJ5bG9uZ3NlY3JldGtleWZvcmhhc2hpbmc=}
jwt.expiration=3600000